filters:
  comments: true
plugins:
  "@textlint/markdown":
    extensions: .md
rules:
  no-todo: true # - [ ] や todo があるとエラーになる
  spellcheck-tech-word: true
  preset-ja-technical-writing:
    sentence-length:
      max: 110
